name: casino_test
description: Casino test application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  http: ^0.13.4
  json_annotation: ^4.4.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.13.0
  json_serializable: ^6.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
